RelativeURLs=true
CanonifyURLs=true
languageCode = "en-US"
defaultContentLanguage = "en"

title = "AWS IoT EduKit"
theme = "learn"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

uglyurls = true
sectionPagesMenu = "main"
pygmentsCodeFences = true
pygmentsStyle = "monokai"

[params]
  description = "AWS IoT EduKit"
  author = "Rashed Talukder, Ryan Burke, Z Sun, Eric Fahsl"
  disableBreadcrumb = false
  disableNextPrev = false
  themeVariant = "aws"
  disableSearch = false
  disableAssetsBusting = true
  disableLanguageSwitchingButton = false
  disableShortcutsTitle = true
  disableInlineCopyToClipBoard = true

[outputs]
home = [ "HTML", "RSS", "JSON"]

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[Languages]
[Languages.en]
title = "AWS IoT EduKit"
weight = 1
languageName = "English"
[Languages.de]
title = "AWS IoT EduKit"
weigth = 3
languageName = "Deutsch"
[Languages.jp]
title = "AWS IoT EduKit"
weight = 1
languageName = "日本語"

[[Languages.en.menu.shortcuts]]
name = '<i class="fas fa-cogs"></i> Installation Instructions'
url = "/getting-started/prerequisites.html"
weight = 0

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-github'></i> Code Repository (<i class='fas fa-sync-alt fa-xs'></i> Apr 16, 2021)"
url = "https://github.com/m5stack/Core2-for-AWS-IoT-EduKit"
weight = 1

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-question-circle'></i> Community Support"
url = "https://github.com/aws-samples/aws-iot-edukit-tutorials/discussions"
weight = 2

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-bug'></i> Report Bugs"
url = "https://github.com/m5stack/Core2-for-AWS-IoT-EduKit/issues"
weight = 3

[menu]
  [[menu.main]]
    identifier = " "
    name = " "
    title = " "
    url = "/"
    weight = -110

[[menu.shortcuts]]
name = "<i class='fab fa-github'></i> Code Repository (<i class='fas fa-sync-alt fa-xs'></i> Apr 6, 2021)"
url = "https://github.com/m5stack/Core2-for-AWS-IoT-EduKit"
weight = 1

[[menu.shortcuts]]
name = "<i class='fas fa-question-circle'></i> Community Support"
url = "https://github.com/aws-samples/aws-iot-edukit-tutorials/discussions"
weight = 2

[[menu.shortcuts]]
name = "<i class='fas fa-bug'></i> Report Bugs"
url = "https://github.com/m5stack/Core2-for-AWS-IoT-EduKit/issues"
weight = 3